### ISSUE TITLE
Include error causing compilation error on Ubuntu

### ISSUE THREAD

**Issue by neginja** [luigivieira/Facial-Landmarks-Annotation-Tool#1]
Hello,

A missing capital letter in the file src/facefitconfig.cpp line 23 causes a compilation error on Ubuntu 16.04 with cmake 3.5.1.

Replacing `#include <QPushbutton>` by `#include <QPushButton>` solve the problem.

Thank you for sharing your work, greetings !

**Comment by luigivieira** [comment]
Hi there mate. Thank you for point that out. I have just fixed it.
I am glad you liked my work. You are welcome! :)

Cheers.
