### ISSUE TITLE
Compiling error with VS 2017

### ISSUE THREAD

**Issue by abdou31** [luigivieira/Facial-Landmarks-Annotation-Tool#11]
Hello , 
I have cloned ,configure and generated the project with Cmake , but when i tried to compile FLAT.sln with Visual Studio 2017 ( Release x64 ) , i get some errors : 
> C3615 error 

![image](https://user-images.githubusercontent.com/19480228/58266024-26664300-7d81-11e9-8eb7-05a9b69ce014.png)

How can i solve this?

**Comment by luigivieira** [comment]
Hi there. Despite the fact that the error messages are in French, the error is in the file `quuid.h` which is a file from Qt. Are you using a newer version than the one supported (indicated in the Readme)? If you are, you might have to change the code to support the changes/updates in Qt. The error message seems to indicate that a UUID (Unique Identifier) is trying to be assigned (=) into a constant expression. Check the call stack of that error and verify if you can change anything in the code to fix it. It is hard to give any more hints based on only a screenshot of the error messages (in French). :)

**Comment by abdou31** [comment]
Problem solved after installing Qt 5.11.0 instead of Qt 5.5

**Comment by luigivieira** [comment]
Interesting. And weird. :) But I am glad you fixed it. Cheers.

**Comment by abdou31** [comment]
Thanks :)

**Comment by luigivieira** [comment]
Easy! Glad to help.

**Comment by abdou31** [comment]
Do you can help me to generate .pts files ( annotation files )?

**Comment by luigivieira** [comment]
Sorry mate. I am working very hard these days on other projects and do not have much spare time to help you in a more "hands on" fashion. But what is your difficulty? Those files are simple text files which you can write in a very similar fashion to how there are read in the [Utils class](https://github.com/luigivieira/Facial-Landmarks-Annotation-Tool/blob/master/src/utils.cpp#L98).

**Comment by abdou31** [comment]
I have a cnn facial landmarks project that uses .pts files annotation , so for that reason i need this , Do you can give me what file should i change to modifiy the extension ?

**Comment by luigivieira** [comment]
I don't know which file(s) you should change. That depends on what exactly you want to do. First you mentioned that you wanted to import the landmarks in bulk, then you say that you want to generate pts files. I gave you a lot of hints (with links to the code) in this and in the other thread, but I can not do the work for you. From the links I have shown you before, you are able to read and/or write pts files. The rest is up to you. You might want to add a new feature to the main window, case in which the code will probably be in mainwindow.cpp. But it could be in another class which you could reference from the main window. Again, that is up to you.

**Comment by abdou31** [comment]
Okey Thanks , 
I see this now , that generate .pts , so the only thing that i want is to generate folder that contains images of dataset , for this i will try to modify the code to get what i want ;)

**Comment by luigivieira** [comment]
You are welcome! Good luck! :)

**Comment by abdou31** [comment]
Thanks my friend :)
