### ISSUE TITLE
Load dataset image folder 

### ISSUE THREAD

**Issue by abdou31** [luigivieira/Facial-Landmarks-Annotation-Tool#12]
Hello ,
I want to know how can i load dataset folder for exemple ( Nice or Helen dataset ) to this tools?
Thanks

**Comment by luigivieira** [comment]
Hey. How are things?

By "load a dataset folder" do you mean to have all images opened in the tool and the landmarks automatically imported from a given source (text file, for instance) in the folder? If yes, the tool does not support that currently. You can definitely load the images to create a new face annotation dataset, but the features will not be automatically loaded from your source.

You can implement that yourself, though. Feel free to fork the project and change it as it fits your needs. :)

In this case, look at the method `void ft::MainWindow::onFitFinished(int iExitCode, QProcess::ExitStatus eExitStatus)` in mainwindow.cpp. That method (an event for when the fitting from the external tool finishes) reads the data from a file and calls `pChild->positionFeatures(vPoints);` from childwindow.cpp to position the features. It is as easy as that.

Good luck.

**Comment by abdou31** [comment]
No , I didn't mean that , i mean open folder of dataset folder image instead of one image just to accelerate the processus ( annotation of dataset )

**Comment by luigivieira** [comment]
You can add multiple images in the same folder by simply selecting them (with SHIFT or CTRL pressed, for instance). But if you want to have a "open all images in the given folder - recursively or not", you will have to implement yourself because again that is a non-existent feature in current version.

**Comment by abdou31** [comment]
Okey , can you tell me how can i generate .pts files after annotating images?

**Comment by luigivieira** [comment]
As I said in the other thread, they are simple text files that you can generate with the same structure as they are read in the helper code from the [Utils class](https://github.com/luigivieira/Facial-Landmarks-Annotation-Tool/blob/master/src/utils.cpp#L98).

**Comment by luigivieira** [comment]
Nonetheless, the tool ALREADY exports pts files, as you can see [in this code](https://github.com/luigivieira/Facial-Landmarks-Annotation-Tool/blob/master/src/mainwindow.cpp#L389).

**Comment by abdou31** [comment]
Can you tell me in what source file can i change the code to load from folder ?

**Comment by luigivieira** [comment]
The interaction actions are all in mainwindow.cpp or childwindow.cpp. The loading functions are all in mainwindow.cpp.
