### ISSUE TITLE
generate .fad file

### ISSUE THREAD

**Issue by fengyeyushi** [luigivieira/Facial-Landmarks-Annotation-Tool#14]
hello :
       thank you for your opensource tool, the tool need the .fad file ,but i have no idea  about how to generate it

**Comment by luigivieira** [comment]
Hi @fengyeyushi. I am glad you liked the tool. A FAD (Face Annotation Dataset) file is simply the file where the tool saves the landmarks annotated for a set of images. It is a common XML file, as you can see from the example in the repo: https://github.com/luigivieira/Facial-Landmarks-Annotation-Tool/blob/master/example/example.fad

After setting up the annotations for your images, you can simply save that data to a FAD file.
