### ISSUE TITLE
Parse the .fad file

### ISSUE THREAD

**Issue by RishikaVarshiiniRao** [luigivieira/Facial-Landmarks-Annotation-Tool#15]
Hi,

I need some help on how to read the contents of the fad file.
Is it similar to an xml file?

**Comment by luigivieira** [comment]
Hi there. Yes, it is a XML file. This is how it is read in the source code: https://github.com/luigivieira/Facial-Landmarks-Annotation-Tool/blob/master/src/facedataset.cpp#L48-L125
