### ISSUE TITLE
Cmake configuration error

### ISSUE THREAD

**Issue by rclim-11** [luigivieira/Facial-Landmarks-Annotation-Tool#5]
Hi, 
I tried to configure the environment in Cmake and received the following error: 

> CMake Error at CMakeLists.txt:48 (find_package):
>   By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5Core", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5Core" with any
>   of the following names:
> 
>     Qt5CoreConfig.cmake
>     qt5core-config.cmake
> 
>   Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
>   "Qt5Core_DIR" to a directory containing one of the above files.  If
>   "Qt5Core" provides a separate development package or SDK, be sure it has
>   been installed.

Sorry if I didn't quite understand the build instructions but is Qt installation necessary?

**Comment by luigivieira** [comment]
Hi there. Yes, Qt is a dependency because the application uses it to render all its graphical user interface. You will have to install it before compiling this application.

**Comment by mrgloom** [comment]
Get same on Mac OS 10.13.6, QT was installed via `brew install qt`

`brew info Qt5`

```
qt: stable 5.11.2 (bottled), HEAD [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt/5.11.2 (9,502 files, 305.2MB)
  Poured from bottle on 2018-11-09 at 01:42:57
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb
==> Dependencies
Build: pkg-config ✔
Optional: mysql-client ✘, postgresql ✘
==> Requirements
Build: xcode ✔
==> Options
--with-examples
	Build examples
--with-mysql-client
	Build with mysql-client support
--with-postgresql
	Build with postgresql support
--without-proprietary-codecs
	Don't build with proprietary codecs (e.g. mp3)
--HEAD
	Install HEAD version
==> Caveats
We agreed to the Qt open source license for you.
If this is unacceptable you should uninstall.

qt is keg-only, which means it was not symlinked into /usr/local,
because Qt 5 has CMake issues when linked.

If you need to have qt first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile

For compilers to find qt you may need to set:
  export LDFLAGS="-L/usr/local/opt/qt/lib"
  export CPPFLAGS="-I/usr/local/opt/qt/include"

For pkg-config to find qt you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

==> Analytics
install: 32,373 (30 days), 90,899 (90 days), 403,453 (365 days)
install_on_request: 13,738 (30 days), 40,983 (90 days), 180,996 (365 days)
build_error: 0 (30 days)
```

`mkdir build && cd build && cmake ..`

```
CMake Error at CMakeLists.txt:48 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by mrgloom** [comment]
Looks like it can be fixed like `cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt/`

**Comment by luigivieira** [comment]
Hi mrgloom. You can fix like that, or have Qt properly configured in your environment. Pay attention to the very end of the output of your `brew info Qt5`, where it states that:

"[...]

If you need to have qt first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile

For compilers to find qt you may need to set:
  export LDFLAGS="-L/usr/local/opt/qt/lib"
  export CPPFLAGS="-I/usr/local/opt/qt/include"

For pkg-config to find qt you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

[...]"
