### ISSUE TITLE
Does it work on Mac?

### ISSUE THREAD

**Issue by volkanunsal** [luigivieira/Facial-Landmarks-Annotation-Tool#6]
Hi, I'm wondering if it will work on my Mac. 

Also, how can I build this? I'm confused by the instructions in the readme. 

Thanks.

**Comment by luigivieira** [comment]
Hi there. I have tested only in Windows and Linux, but it should work on Mac as long as you have installed the dependencies (mainly Qt).

To build you will have to first install [CMake](https://cmake.org/), then run it for the CMakeLists.txt in the project. CMake will generate the Makefiles for you to use when building the application. The instructions are pretty much that. If you have built some other C++ code before you should not have any difficulty with it.
