### ISSUE TITLE
Landmark dot size

### ISSUE THREAD

**Issue by mrgloom** [luigivieira/Facial-Landmarks-Annotation-Tool#9]
Is it possible to make landmark dot size smaller? when I use tool with images lower then ~400pix it hard to see details.

**Comment by luigivieira** [comment]
Yes, it is. Change the [radius of the feature nodes](https://github.com/luigivieira/Facial-Landmarks-Annotation-Tool/blob/master/src/facefeaturenode.cpp#L30).
